### ISSUE TITLE
[REQUEST] Define documentation describing absolute bare-minimum setup

### ISSUE THREAD

**Issue by axtens** [openmainframeproject/cobol-check#218]
I'm setting up a gnucobol track on Exercism.org. I'm currently trying to establish the absolute bare-minimum setup so that I can create completely self-contained tasks. Granted, the gnucobol compiler itself won't be part of the container but I'm considering including the cobol-check binary and relatively-pathed configuration files.

Where do I begin?

**Comment by dakaa16** [comment]
Hi @axtens thank you for your interest in Cobol Check. I have described the smallest setup you can currently make with Cobol Check [here](https://github.com/openmainframeproject/cobol-check/wiki/Getting-Started#minimal-setup), do let me know, if something isn't clear. The problem with your setup is that your test-file is required to be inside a folder, with a name matching your source program. So inside your test folder, should be a folder named 'hello-world' and inside that folder you may have all your tests, named whatever you want.

**Comment by dakaa16** [comment]
Also; I'd like to know where you got your distribution, as it's only very outdated distributions you can get online

**Comment by axtens** [comment]
Hello @daaka16, and thank you for your assistance.

Regarding version I have
c:\Users\bugma\Dropbox\Projects\gnucobol\exercises\practice\hello-world>echo
off
CobolCheck: INFO 2022-07-08T12:38:07.739582500Z INF001: Attempting to load
config from config.properties.
CobolCheck: INFO 2022-07-08T12:38:07.752592500Z INF002: Loaded config
successfully from config.properties.
Version: 0.1.0

I am finding your instructions problematic. Here's my directory structure:

C:.
|   cobolcheck
|   cobolcheck.cmd
|   config.properties
|
+---.docs
|       instructions.md
|
+---.meta
|       config.json
|
+---bin
|       cobol-check-0.1.0.jar
|
+---hello-world
|       hello-world
|
+---scripts
|       linux_gnucobol_run_tests
|       windows_gnucobol_run_tests.cmd
|
\---src
        hello-world.cbl

When I run cobolcheck I get

c:\Users\bugma\Dropbox\Projects\gnucobol\exercises\practice\hello-world>cobolcheck

c:\Users\bugma\Dropbox\Projects\gnucobol\exercises\practice\hello-world>echo
off
CobolCheck: INFO 2022-07-08T12:52:20.964858600Z INF001: Attempting to load
config from config.properties.
CobolCheck: INFO 2022-07-08T12:52:20.972852200Z INF002: Loaded config
successfully from config.properties.
CobolCheck: INFO 2022-07-08T12:52:20.974860400Z INF001: Attempting to load
config from config.properties.
CobolCheck: INFO 2022-07-08T12:52:20.975862400Z INF002: Loaded config
successfully from config.properties.
CobolCheck: INFO 2022-07-08T12:52:20.975862400Z INF003: Cobol-Check starting
CobolCheck: INFO 2022-07-08T12:52:20.975862400Z INF005: Log level is INFO.
CobolCheck: INFO 2022-07-08T12:52:20.975862400Z INF006: Configuration
settings: production.
CobolCheck: INFO 2022-07-08T12:52:20.982854100Z WRN001: No test suite
directory for program  was found under directory src\.
CobolCheck: INFO 2022-07-08T12:52:20.982854100Z INF004: Cobol-Check
terminating
cobc: hello-world.CBL: No such file or directory

Kind regards,
Bruce.

**Comment by dakaa16** [comment]
Your hello-world folder should be inside your src folder. That should fix it.

**Comment by axtens** [comment]
Sadly, that didn't fix the problem.

So I've boiled my config.properties down to just the three lines your guide
described, viz
application.source.directory = src
application.copybook.directory = src
test.suite.directory = src

Tree is now

C:.
|   cobolcheck
|   cobolcheck.cmd
|   config.properties
|
+---.docs
|       instructions.md
|
+---.meta
|       config.json
|
+---bin
|       cobol-check-0.1.0.jar
|
+---scripts
|       linux_gnucobol_run_tests
|       windows_gnucobol_run_tests.cmd
|
\---src
    |   hello-world.cbl
    |
    \---hello-world
            hello-world.cut

And a run with debug level logging gives

c:\Users\bugma\Dropbox\Projects\gnucobol\exercises\practice\hello-world>cobolcheck
-l debug

c:\Users\bugma\Dropbox\Projects\gnucobol\exercises\practice\hello-world>echo
off
Could Not Find
c:\Users\bugma\Dropbox\Projects\gnucobol\exercises\practice\hello-world\hello-world*
CobolCheck: INFO 2022-07-08T13:27:48.229230400Z INF001: Attempting to load
config from config.properties.
CobolCheck: INFO 2022-07-08T13:27:48.235590600Z INF002: Loaded config
successfully from config.properties.
CobolCheck: INFO 2022-07-08T13:27:48.239627600Z INF001: Attempting to load
config from config.properties.
CobolCheck: INFO 2022-07-08T13:27:48.240724600Z INF002: Loaded config
successfully from config.properties.
CobolCheck: DEBUG 2022-07-08T13:27:48.241619600Z INF003: Cobol-Check
starting
CobolCheck: DEBUG 2022-07-08T13:27:48.241619600Z INF005: Log level is DEBUG.
CobolCheck: DEBUG 2022-07-08T13:27:48.241619600Z INF006: Configuration
settings: .
CobolCheck: DEBUG 2022-07-08T13:27:48.242634700Z
StringHelper.adjustPathString() original string: <src>
CobolCheck: DEBUG 2022-07-08T13:27:48.242634700Z
StringHelper.adjustPathString() Constants.FILE_SEPARATOR: <\>
CobolCheck: DEBUG 2022-07-08T13:27:48.242634700Z
StringHelper.adjustPathString() os.name is <Windows 11>
CobolCheck: DEBUG 2022-07-08T13:27:48.242634700Z
StringHelper.adjustStringPath() result is <src>
CobolCheck: DEBUG 2022-07-08T13:27:48.247640700Z WRN001: No test suite
directory for program  was found under directory src\.
CobolCheck: DEBUG 2022-07-08T13:27:48.247640700Z INF004: Cobol-Check
terminating
cobc: hello-world.CBL: No such file or directory

Kind regards,
Bruce

**Comment by dakaa16** [comment]
Hi Bruce, I'll be off for the weekend, so let's figure out what goes wrong on Monday. I don't feel like this is the right forum, so please contact me on dak@bankdata.dk, then we can discuss this further - perhaps an online meeting would be the quickest way to figure out what goes wrong. Have a great weekend.

Best regards
David
